set(_AMENT_PACKAGE_NAME "sweepi_robot_manager")
set(sweepi_robot_manager_VERSION "0.1.0")
set(sweepi_robot_manager_MAINTAINER "akhila-wedamestrige <wedamestrigean@gmail.com>")
set(sweepi_robot_manager_BUILD_DEPENDS "rclpy" "std_msgs" "std_srvs" "nav2_msgs" "sweepi_robot_manager_interfaces")
set(sweepi_robot_manager_BUILDTOOL_DEPENDS "ament_cmake" "ament_cmake_python")
set(sweepi_robot_manager_BUILD_EXPORT_DEPENDS "rclpy" "std_msgs" "std_srvs" "nav2_msgs" "sweepi_robot_manager_interfaces")
set(sweepi_robot_manager_BUILDTOOL_EXPORT_DEPENDS )
set(sweepi_robot_manager_EXEC_DEPENDS "ament_index_python" "launch" "launch_ros" "sweepi_bringup" "sweepi_exploration" "sweepi_coverage" "sweepi_api_bridge" "sweepi_real_bringup" "nav2_bringup" "rviz2" "rclpy" "std_msgs" "std_srvs" "nav2_msgs" "sweepi_robot_manager_interfaces")
set(sweepi_robot_manager_TEST_DEPENDS "ament_copyright" "ament_flake8" "ament_pep257" "python3-pytest")
set(sweepi_robot_manager_GROUP_DEPENDS )
set(sweepi_robot_manager_MEMBER_OF_GROUPS )
set(sweepi_robot_manager_DEPRECATED "")
set(sweepi_robot_manager_EXPORT_TAGS)
list(APPEND sweepi_robot_manager_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
