set(_AMENT_PACKAGE_NAME "sweepi_slam")
set(sweepi_slam_VERSION "0.0.0")
set(sweepi_slam_MAINTAINER "akhila-wedamestrige <wedamestrigean@gmail.com>")
set(sweepi_slam_BUILD_DEPENDS "rclcpp" "sensor_msgs" "nav_msgs" "geometry_msgs" "tf2_ros" "tf2" "std_msgs" "slam_toolbox" "nav2_map_server" "rviz2" "visualization_msgs")
set(sweepi_slam_BUILDTOOL_DEPENDS "ament_cmake")
set(sweepi_slam_BUILD_EXPORT_DEPENDS "rclcpp" "sensor_msgs" "nav_msgs" "geometry_msgs" "tf2_ros" "tf2" "std_msgs" "slam_toolbox" "nav2_map_server" "rviz2" "visualization_msgs")
set(sweepi_slam_BUILDTOOL_EXPORT_DEPENDS )
set(sweepi_slam_EXEC_DEPENDS "rclcpp" "sensor_msgs" "nav_msgs" "geometry_msgs" "tf2_ros" "tf2" "std_msgs" "slam_toolbox" "nav2_map_server" "rviz2" "visualization_msgs")
set(sweepi_slam_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(sweepi_slam_GROUP_DEPENDS )
set(sweepi_slam_MEMBER_OF_GROUPS )
set(sweepi_slam_DEPRECATED "")
set(sweepi_slam_EXPORT_TAGS)
list(APPEND sweepi_slam_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
