set(_AMENT_PACKAGE_NAME "sweepi_real_bringup")
set(sweepi_real_bringup_VERSION "0.1.0")
set(sweepi_real_bringup_MAINTAINER "akhila-wedamestrige <wedamestrigean@gmail.com>")
set(sweepi_real_bringup_BUILD_DEPENDS )
set(sweepi_real_bringup_BUILDTOOL_DEPENDS "ament_cmake")
set(sweepi_real_bringup_BUILD_EXPORT_DEPENDS )
set(sweepi_real_bringup_BUILDTOOL_EXPORT_DEPENDS )
set(sweepi_real_bringup_EXEC_DEPENDS "launch" "launch_ros" "robot_state_publisher" "xacro" "sllidar_ros2" "sweepi_base_driver" "sweepi_description" "sweepi_state_estimation" "sweepi_temp_rpi_hardware")
set(sweepi_real_bringup_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(sweepi_real_bringup_GROUP_DEPENDS )
set(sweepi_real_bringup_MEMBER_OF_GROUPS )
set(sweepi_real_bringup_DEPRECATED "")
set(sweepi_real_bringup_EXPORT_TAGS)
list(APPEND sweepi_real_bringup_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
