set(_AMENT_PACKAGE_NAME "sweepi_state_estimation")
set(sweepi_state_estimation_VERSION "0.1.0")
set(sweepi_state_estimation_MAINTAINER "akhila-wedamestrige <wedamestrigean@gmail.com>")
set(sweepi_state_estimation_BUILD_DEPENDS )
set(sweepi_state_estimation_BUILDTOOL_DEPENDS "ament_cmake")
set(sweepi_state_estimation_BUILD_EXPORT_DEPENDS )
set(sweepi_state_estimation_BUILDTOOL_EXPORT_DEPENDS )
set(sweepi_state_estimation_EXEC_DEPENDS "launch" "launch_ros" "robot_localization")
set(sweepi_state_estimation_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(sweepi_state_estimation_GROUP_DEPENDS )
set(sweepi_state_estimation_MEMBER_OF_GROUPS )
set(sweepi_state_estimation_DEPRECATED "")
set(sweepi_state_estimation_EXPORT_TAGS)
list(APPEND sweepi_state_estimation_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
