set(_AMENT_PACKAGE_NAME "sweepi_description")
set(sweepi_description_VERSION "0.0.0")
set(sweepi_description_MAINTAINER "akhila-wedamestrige <wedamestrigean@gmail.com>")
set(sweepi_description_BUILD_DEPENDS )
set(sweepi_description_BUILDTOOL_DEPENDS "ament_cmake")
set(sweepi_description_BUILD_EXPORT_DEPENDS )
set(sweepi_description_BUILDTOOL_EXPORT_DEPENDS )
set(sweepi_description_EXEC_DEPENDS )
set(sweepi_description_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(sweepi_description_GROUP_DEPENDS )
set(sweepi_description_MEMBER_OF_GROUPS )
set(sweepi_description_DEPRECATED "")
set(sweepi_description_EXPORT_TAGS)
list(APPEND sweepi_description_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
