set(_AMENT_PACKAGE_NAME "sweepi_coverage")
set(sweepi_coverage_VERSION "0.1.0")
set(sweepi_coverage_MAINTAINER "akhila-wedamestrige <wedamestrigean@gmail.com>")
set(sweepi_coverage_BUILD_DEPENDS "rclpy" "std_msgs" "std_srvs" "nav_msgs" "geometry_msgs" "sensor_msgs" "action_msgs" "nav2_msgs" "tf2_ros" "visualization_msgs")
set(sweepi_coverage_BUILDTOOL_DEPENDS "ament_cmake" "ament_cmake_python")
set(sweepi_coverage_BUILD_EXPORT_DEPENDS "rclpy" "std_msgs" "std_srvs" "nav_msgs" "geometry_msgs" "sensor_msgs" "action_msgs" "nav2_msgs" "tf2_ros" "visualization_msgs")
set(sweepi_coverage_BUILDTOOL_EXPORT_DEPENDS )
set(sweepi_coverage_EXEC_DEPENDS "ament_index_python" "launch" "launch_ros" "rclpy" "std_msgs" "std_srvs" "nav_msgs" "geometry_msgs" "sensor_msgs" "action_msgs" "nav2_msgs" "tf2_ros" "visualization_msgs")
set(sweepi_coverage_TEST_DEPENDS "ament_copyright" "ament_cmake_pytest" "ament_flake8" "ament_pep257" "python3-pytest")
set(sweepi_coverage_GROUP_DEPENDS )
set(sweepi_coverage_MEMBER_OF_GROUPS )
set(sweepi_coverage_DEPRECATED "")
set(sweepi_coverage_EXPORT_TAGS)
list(APPEND sweepi_coverage_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
