set(_AMENT_PACKAGE_NAME "sweepi_exploration")
set(sweepi_exploration_VERSION "0.2.0")
set(sweepi_exploration_MAINTAINER "akhila-wedamestrige <wedamestrigean@gmail.com>")
set(sweepi_exploration_BUILD_DEPENDS "rclpy" "std_msgs" "nav_msgs" "geometry_msgs" "sensor_msgs" "action_msgs" "std_srvs" "nav2_msgs" "sweepi_slam" "visualization_msgs")
set(sweepi_exploration_BUILDTOOL_DEPENDS "ament_cmake" "ament_cmake_python")
set(sweepi_exploration_BUILD_EXPORT_DEPENDS "rclpy" "std_msgs" "nav_msgs" "geometry_msgs" "sensor_msgs" "action_msgs" "std_srvs" "nav2_msgs" "sweepi_slam" "visualization_msgs")
set(sweepi_exploration_BUILDTOOL_EXPORT_DEPENDS )
set(sweepi_exploration_EXEC_DEPENDS "rclpy" "std_msgs" "nav_msgs" "geometry_msgs" "sensor_msgs" "action_msgs" "std_srvs" "nav2_msgs" "sweepi_slam" "visualization_msgs")
set(sweepi_exploration_TEST_DEPENDS "ament_copyright" "ament_flake8" "ament_pep257" "python3-pytest")
set(sweepi_exploration_GROUP_DEPENDS )
set(sweepi_exploration_MEMBER_OF_GROUPS )
set(sweepi_exploration_DEPRECATED "")
set(sweepi_exploration_EXPORT_TAGS)
list(APPEND sweepi_exploration_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
