# generated from colcon_core/shell/template/command_prefix.sh.em
. "/home/sweepi/SweePi/install_diagnostic/sllidar_ros2/share/sllidar_ros2/package.sh"
. "/home/sweepi/SweePi/install_diagnostic/sweepi_base_driver/share/sweepi_base_driver/package.sh"
. "/home/sweepi/SweePi/install_diagnostic/sweepi_coverage/share/sweepi_coverage/package.sh"
. "/home/sweepi/SweePi/install_diagnostic/sweepi_description/share/sweepi_description/package.sh"
. "/home/sweepi/SweePi/install_diagnostic/sweepi_robot_manager_interfaces/share/sweepi_robot_manager_interfaces/package.sh"
. "/home/sweepi/SweePi/install_diagnostic/sweepi_slam/share/sweepi_slam/package.sh"
. "/home/sweepi/SweePi/install_diagnostic/sweepi_state_estimation/share/sweepi_state_estimation/package.sh"
. "/home/sweepi/SweePi/install_diagnostic/sweepi_temp_rpi_hardware/share/sweepi_temp_rpi_hardware/package.sh"
. "/home/sweepi/SweePi/install_diagnostic/sweepi_api_bridge/share/sweepi_api_bridge/package.sh"
. "/home/sweepi/SweePi/install_diagnostic/sweepi_bringup/share/sweepi_bringup/package.sh"
. "/home/sweepi/SweePi/install_diagnostic/sweepi_exploration/share/sweepi_exploration/package.sh"
. "/home/sweepi/SweePi/install_diagnostic/sweepi_real_bringup/share/sweepi_real_bringup/package.sh"
