set(_AMENT_PACKAGE_NAME "sweepi_bringup")
set(sweepi_bringup_VERSION "0.0.0")
set(sweepi_bringup_MAINTAINER "akhila-wedamestrige <wedamestrigean@gmail.com>")
set(sweepi_bringup_BUILD_DEPENDS "rclpy" "rclcpp" "geometry_msgs" "sensor_msgs" "nav_msgs" "rosgraph_msgs" "tf2" "tf2_ros" "std_msgs" "gazebo" "gazebo_ros" "gazebo_ros2_control" "gz_ros2_control" "ros_gz" "ros_gz_sim" "ros_gz_bridge" "robot_state_publisher" "joint_state_publisher" "joint_state_publisher_gui" "urdf" "xacro" "controller_manager" "diff_drive_controller" "rviz2" "rviz_common" "sweepi_description" "sweepi_slam")
set(sweepi_bringup_BUILDTOOL_DEPENDS "ament_cmake")
set(sweepi_bringup_BUILD_EXPORT_DEPENDS "rclpy" "rclcpp" "geometry_msgs" "sensor_msgs" "nav_msgs" "rosgraph_msgs" "tf2" "tf2_ros" "std_msgs" "gazebo" "gazebo_ros" "gazebo_ros2_control" "gz_ros2_control" "ros_gz" "ros_gz_sim" "ros_gz_bridge" "robot_state_publisher" "joint_state_publisher" "joint_state_publisher_gui" "urdf" "xacro" "controller_manager" "diff_drive_controller" "rviz2" "rviz_common" "sweepi_description" "sweepi_slam")
set(sweepi_bringup_BUILDTOOL_EXPORT_DEPENDS )
set(sweepi_bringup_EXEC_DEPENDS "rclpy" "rclcpp" "geometry_msgs" "sensor_msgs" "nav_msgs" "rosgraph_msgs" "tf2" "tf2_ros" "std_msgs" "gazebo" "gazebo_ros" "gazebo_ros2_control" "gz_ros2_control" "ros_gz" "ros_gz_sim" "ros_gz_bridge" "robot_state_publisher" "joint_state_publisher" "joint_state_publisher_gui" "urdf" "xacro" "controller_manager" "diff_drive_controller" "rviz2" "rviz_common" "sweepi_description" "sweepi_slam")
set(sweepi_bringup_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(sweepi_bringup_GROUP_DEPENDS )
set(sweepi_bringup_MEMBER_OF_GROUPS )
set(sweepi_bringup_DEPRECATED "")
set(sweepi_bringup_EXPORT_TAGS)
list(APPEND sweepi_bringup_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
